services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'community-nexus'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./database/data-mysql:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    networks:
      - community-nexus
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./database/data-redis:/data
    networks:
      - community-nexus
    depends_on:
      - db

networks:
  community-nexus:
    driver: bridge
